# Dockerfile.node
FROM node:18.18.0-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# INSTALAMOS PM2, PARA PRODUCCIÓN DE LA API
RUN npm install pm2 -g

# COMANDO PARA EJECUTAR
CMD ["pm2-runtime", "index.mjs"]