# Dockerfile.nginx
FROM nginx:1.25.4-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
# Comando para verificar la configuración y reiniciar Nginx
CMD ["sh", "-c", "nginx -t && nginx -g 'daemon off;'"]